all:
  hosts:
    rpi-servicebox:
      ansible_host: 192.168.43.96
      ansible_user: mqttserver
      node_red_enabled: true
      ar_iot_server_repo_url: "https://github.com/DominikZurawski/AR-IoT-ServiceBox"
      ar_iot_server_repo_version: main
      ar_iot_server_mqtt_host: 127.0.0.1
